/**
 * This file is generated by acribus-cli
 * DO NOT modify this file!
 */

import Vue from 'vue'
import Vuex from 'vuex'

import menu from './modules/menu'

Vue.use(Vuex)

export default new Vuex.Store({
  modules: {
    menu
  }
})
